create database multitenant;
create schema tenant1;
create schema tenant2;
create table tenant1.employee (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tenant2.employee (id int8 generated by default as identity, name varchar(255), primary key (id));